#!/usr/bin/env bash
# git-push-retry.sh <remote-url> [branch]
#
# Push HEAD:<branch> (default: main) to <remote-url> with retry-on-conflict.
# Multiple loops (team-learning-loop / ad-lp-daily-learning / ad-lp-apply-daily /
# research-team-learning / seo-daily / ad-pdca-daily) can run concurrently and
# all push generated changes (learnings, decisions.md, etc.) back to the same
# repo/branch (ai-ops-config or ai-business-ops). A plain `git push` races and
# non-fast-forward-rejects whichever run loses. Real-world hit: seo-daily and
# ad-lp-daily-learning both pushed to ai-business-ops within the same minute
# and one was rejected.
#
# Fix: on rejection, fetch + rebase onto the remote tip and retry. Content is
# append-only markdown (learnings/decisions logs), so a rebase almost never
# conflicts; if it somehow does, fall back to a plain merge (--no-edit) rather
# than aborting the whole loop, and worst case keep both sides via `git merge
# -X ours`+manual concat is overkill here -- see .gitattributes (merge=union)
# added to ai-ops-config/ai-business-ops for the actual append-only files,
# which makes git auto-resolve concurrent appends to the same file cleanly.
#
# 2026-08-01 fix (real failure: zerosys-transport-ads-daily-pdca run
# 30696348613, 5/5 attempts failed): three bugs found and fixed here.
# (1) When the plain-merge fallback ALSO failed with conflicts, the script
#     printed "giving up this attempt" but never ran `git merge --abort`,
#     leaving the working tree mid-merge with unresolved conflicts. Every
#     subsequent retry attempt then failed immediately with "cannot rebase:
#     you have unstaged changes / needs merge" -- turning one recoverable
#     conflict into a guaranteed 5/5 failure. Fixed by aborting the merge
#     before the loop retries, same as the existing `git rebase --abort`
#     cleanup.
# (2) The actual conflicts were in `memory/ad-metrics/**/*.json` and
#     `memory/*-status.json` -- machine-generated snapshot/cache files that
#     get wholesale-regenerated by their own loop on every run (their own
#     header comments say so, e.g. "このファイルはダッシュボード表示専用の
#     集計値" -- explicitly NOT a source of truth). These are not append-only
#     history like decisions.md/learnings/*.md (which .gitattributes already
#     handles via merge=union), so real conflicts are expected whenever two
#     loops touch overlapping files in the same short window. Since losing a
#     stale snapshot to a conflict costs nothing (the next successful run
#     regenerates it fresh), auto-resolve conflicts limited to this specific
#     allowlist by keeping this run's freshly-generated content instead of
#     failing the whole push. Any conflict OUTSIDE this allowlist still
#     aborts and fails loudly -- this is intentionally narrow.
# (3) Caught by a local dry-run test before shipping: `git checkout --ours`
#     means opposite things in a rebase vs a merge (during `git rebase`,
#     "ours" is the upstream/target being rebased ONTO, and "theirs" is the
#     commit being replayed -- backwards from normal merge semantics). A
#     naive `--ours` resolver used for both contexts silently kept the
#     REMOTE's stale content during rebase instead of this run's fresh data
#     (confirmed by cloning two throwaway repos, generating a real conflict,
#     and diffing the pushed result -- it does not match the SKILL's file
#     header comments about semantics, so don't trust intuition here either).
#     Fixed by never auto-resolving inside a rebase: on any rebase conflict,
#     abort immediately and fall through to the merge path, where "ours" is
#     unambiguously this run's local commit.
# Must be run from inside the target git working directory.
set -uo pipefail

REMOTE_URL="${1:?usage: git-push-retry.sh <remote-url> [branch]}"
BRANCH="${2:-main}"
MAX_ATTEMPTS=5

# Paths safe to auto-resolve as "keep ours" on conflict: wholesale-regenerated
# snapshot/cache files only, never narrative logs.
CACHE_ONLY_PATTERN='^memory/ad-metrics/.*\.json$|^memory/[^/]*-status\.json$'

resolve_cache_conflicts_or_abort() {
  # Must only be called during a MERGE (not a rebase -- see note (3) above).
  # Returns 0 if the merge's conflicts were either fully resolved (cache-only)
  # or there were none; returns 1 if any conflict falls outside the allowlist
  # (caller is responsible for aborting in that case).
  local unmerged outside
  unmerged="$(git diff --name-only --diff-filter=U || true)"
  if [ -z "${unmerged}" ]; then
    return 0
  fi
  outside="$(printf '%s\n' "${unmerged}" | grep -vE "${CACHE_ONLY_PATTERN}" || true)"
  if [ -n "${outside}" ]; then
    echo "[git-push-retry] conflict outside cache allowlist, cannot auto-resolve: ${outside}" >&2
    return 1
  fi
  echo "[git-push-retry] auto-resolving cache-only conflicts (keep this run's content): $(printf '%s' "${unmerged}" | tr '\n' ' ')"
  printf '%s\n' "${unmerged}" | xargs -r git checkout --ours --
  printf '%s\n' "${unmerged}" | xargs -r git add --
  return 0
}

for i in $(seq 1 "${MAX_ATTEMPTS}"); do
  if git push "${REMOTE_URL}" "HEAD:${BRANCH}"; then
    echo "[git-push-retry] pushed on attempt ${i}"
    exit 0
  fi
  echo "[git-push-retry] attempt ${i} rejected, fetching + rebasing onto ${BRANCH}..."
  git fetch "${REMOTE_URL}" "${BRANCH}"
  if ! git rebase FETCH_HEAD; then
    echo "[git-push-retry] rebase had conflicts, aborting rebase and trying a plain merge instead"
    git rebase --abort || true
    if ! git merge FETCH_HEAD --no-edit; then
      if resolve_cache_conflicts_or_abort && git commit --no-edit; then
        echo "[git-push-retry] merge conflicts auto-resolved (cache-only), continuing"
      else
        echo "[git-push-retry] merge also failed, giving up this attempt" >&2
        git merge --abort || true
      fi
    fi
  fi
  sleep "$(( (RANDOM % 5) + 2 ))"
done

echo "[git-push-retry] FAILED after ${MAX_ATTEMPTS} attempts" >&2
exit 1
